name: DocFX Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  generate-docs:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - run: ls
        
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        name: Publish Documentation on GitHub Pages
        with:
          branch: gh-pages
          folder: docs/_site