name: Test and publish Scraper.Net.Twitter

on:
  workflow_dispatch:
  push:
   paths:
     - "src/Scraper.Net.Twitter/**"
     - "test/Scraper.Net.Twitter.Tests/**"
  pull_request:
    paths:
      - "src/Scraper.Net.Twitter/**"
      - "test/Scraper.Net.Twitter.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Set secrets
      run: |
        cd test/Scraper.Net.Twitter.Tests
        dotnet user-secrets set ConsumerKey "${{ secrets.TWITTER_CONSUMERKEY }}"
        dotnet user-secrets set ConsumerSecret "${{ secrets.TWITTER_CONSUMERSECRET }}"
        cd ..
      
    - name: Test
      run: dotnet test --no-build test/Scraper.Net.Twitter.Tests

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Scraper.Net.Twitter/Scraper.Net.Twitter.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false