name: Test and publish Scraper.Net.Facebook

on:
  workflow_dispatch:
  push:
   paths:
     - "src/Scraper.Net.Facebook/**"
     - "test/Scraper.Net.Facebook.Tests/**"
  pull_request:
    paths:
      - "src/Scraper.Net.Facebook/**"
      - "test/Scraper.Net.Facebook.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install python dependencies
      run: pip install -r src/Scraper.Net.Facebook/requirements.txt
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build test/Scraper.Net.Facebook.Tests

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Scraper.Net.Facebook/Scraper.Net.Facebook.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false