name: Test and publish Scraper.Net

on:
  push:
   paths:
     - "Scraper.Net/**"
     - "Scraper.Net.Tests/**"
  pull_request:
    paths:
      - "Scraper.Net/**"
      - "Scraper.Net.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build Scraper.Net.Tests

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Scraper.Net/Scraper.Net.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false