name: Test and publish Scraper.Net.YoutubeDl

on:
  push:
  #  paths:
  #    - "Scraper.Net.YoutubeDl/**"
  #    - "Scraper.Net.YoutubeDl.Tests/**"
  pull_request:
    paths:
      - "Scraper.Net.YoutubeDl/**"
      - "Scraper.Net.YoutubeDl.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup youtube-dl
      run: |
        curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ./youtube-dl.exe
        chmod a+rx ./youtube-dl.exe
                
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build Scraper.Net.YoutubeDl.Tests

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Scraper.Net.YoutubeDl/Scraper.Net.YoutubeDl.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false